config/routes.rb
Quattro::Application.routes.draw do
  
  devise_for :users  
  resources :contacts
  resources :companies
  resources :customers
  resources :vehicles
  resources :brands
  resources :models
  resources :bodies
  resources :projects
  resources :services
  resources :project_photo
  resources :action_registrations
  root :to => 'pages#home'
  
  match '/about', :to => 'companies#show'
  match '/admin', :to => 'administration/companies#show'

  
  namespace :administration do
    resources :projects  do
      member do
        put :set_default_photo
      end
    end    
    resources :project_photos
    resources :companies
    resources :action_registrations do
      member do
        put :change_status
      end
    end
    resources :bodies
    resources :brands do
      resources :models
    end
    resources :customers    
    resources :services
    resources :contacts
    resources :users
  end

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :finish_date, :name, :rating
  has_and_belongs_to_many :vehicles
  has_many :project_photos
  has_and_belongs_to_many :services
  validates :description, :presence => true
end

app/controllers/administration/action_registrations_controller.rb
class Administration::ActionRegistrationsController < AdministrationController
  
  # GET /action_registrations
  # GET /action_registrations.json
  def index
    @action_registrations = ActionRegistration.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @action_registrations }
    end
  end

  # GET /action_registrations/1
  # GET /action_registrations/1.json
  def show
    @action_registration = ActionRegistration.find(params[:id])
    @customer = Customer.find_by_id(@action_registration.customer_id)
    @vehicle= Vehicle.find_by_id(@action_registration.vehicle_id)
    if @action_registration.status==true
      @status='Ready'
    else
      @status='Not ready'
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @action_registration }
    end
  end

  # GET /action_registrations/new
  # GET /action_registrations/new.json
  def new
    @action_registration = ActionRegistration.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @action_registration }
    end
  end

  # GET /action_registrations/1/edit
  def edit
    @action_registration = ActionRegistration.find(params[:id])
    @customer = Customer.find_by_id(@action_registration.customer_id)
    @vehicle= Vehicle.find_by_id(@action_registration.vehicle_id)
    @brand=@vehicle.model.brand
    @model=@vehicle.model
    @body=@vehicle.body
    @year=@vehicle.year
    @name=@customer.name
    if (@customer.contacts)
      @email = @customer.contacts.find_by_type(:Email)
      @phone = @customer.contacts.find_by_type(:Phone)
    end
  end

  # POST /action_registrations
  # POST /action_registrations.json
  def create
    @action_registration = ActionRegistration.new

    @brand
    if (params.has_key?(:brand_id) && !params[:brand_id].empty?)
      @brand = Brand.find(params[:brand_id])
    else
      @action_registration.errors.add(:brand_id, "wasn't filled in")
    end

    @model
    if (params.has_key?(:model_id) && !params[:model_id].empty?)
      @model = @brand.models.find(params[:model_id])
    else
      @action_registration.errors.add(:model_id, "wasn't filled in")
    end

    @body
    if (params.has_key?(:body_id) && !params[:body_id].empty?)
      @body = Body.find(params[:body_id])
    else
      @action_registration.errors.add(:body_id, "wasn't filled in")
    end

    @year
    if (params.has_key?(:year) && !params[:year].empty?)
      @year = params[:year]
    else
      @action_registration.errors.add(:year, "wasn't filled in")
    end    

    @customer = Customer.new
    
    @name
    if (params.has_key?(:name) && !params[:name].empty?)
      @customer.name = params[:name]
    else
      @action_registration.errors.add(:name, "wasn't filled in")
    end 
    
    @phone
    if (params.has_key?(:phone) && !params[:phone].empty?)
      @phone = Phone.new({:value => params[:phone]})
      @customer.contacts << @phone
    end 

    @email
    if (params.has_key?(:email) && !params[:email].empty?)
      @email = Email.new({:value => params[:email]})
      @customer.contacts << @email
    end 

    @date=DateTime.now.to_date
    

    if (!@phone && !@email)
      @action_registration.errors.add(:email, ' or phone shuld be filled in')
    end

    saved = false
    if (@action_registration.errors.empty?)
      @vehicle = Vehicle.create({:model => @model, :body => @body, :year => @year})      

      ActionRegistration.transaction do
        @customer.save
        @vehicle.save
        @action_registration = ActionRegistration.new({:vehicle => @vehicle, :customer => @customer, :date => @date, :status => false  })
        @action_registration.save

        saved = true
      end
    end

    respond_to do |format|
      if saved
        format.html { redirect_to administration_action_registration_path(@action_registration), notice: 'Action registration was successfully created.' }
        format.json { render json: @action_registration, status: :created, location: @action_registration }
      else
        format.html { render action: "new" }
        format.json { render json: @action_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /action_registrations/1
  # PUT /action_registrations/1.json
  def update
    @action_registration = ActionRegistration.find(params[:id])

    @brand
    if (params.has_key?(:brand_id) && !params[:brand_id].empty?)
      @brand = Brand.find(params[:brand_id])
    else
      @action_registration.errors.add(:brand_id, "wasn't filled in")
    end

    @model
    if (params.has_key?(:model_id) && !params[:model_id].empty?)
      @model = @brand.models.find(params[:model_id])
    else
      @action_registration.errors.add(:model_id, "wasn't filled in")
    end

    @body
    if (params.has_key?(:body_id) && !params[:body_id].empty?)
      @body = Body.find(params[:body_id])
    else
      @action_registration.errors.add(:body_id, "wasn't filled in")
    end

    @year
    if (params.has_key?(:year) && !params[:year].empty?)
      @year = params[:year]
    else
      @action_registration.errors.add(:year, "wasn't filled in")
    end    

    @customer = Customer.find_by_id(@action_registration.customer_id)
    
    @name
    if (params.has_key?(:name) && !params[:name].empty?)
      @customer.name = params[:name]
    end
    
    @phone
    if (params.has_key?(:phone) && !params[:phone].empty?)
      @customer.contacts.find_by_type(:Phone).update_attributes(value: params[:phone])
    end

    @Email
    if (params.has_key?(:email) && !params[:email].empty?)
      @customer.contacts.find_by_type(:Email).update_attributes(value: params[:email])
    end
    
    @vehicle= Vehicle.find_by_id(@action_registration.vehicle_id)

    @date=DateTime.now.to_date

    if (!@phone && !@email && !@name)
      @action_registration.errors.add(:email, "email or phone or name shuld be filled in")
      @action_registration.errors.add(:phone, "email or phone or name shuld be filled in")      
      @action_registration.errors.add(:name, "email or phone or name shuld be filled in")
    end

    @vehicle.update_attributes({:model => @model, :body => @body, :year => @year})
    @action_registration.update_attributes({:vehicle => @vehicle, :customer => @customer, :date => @date, :status => false  })
    @customer.save

    respond_to do |format|
      if @action_registration.update_attributes(params[:action_registration])
        format.html { redirect_to administration_action_registration_path(@action_registration), notice: 'Action registration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @action_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /action_registrations/1
  # DELETE /action_registrations/1.json
  def destroy
    @action_registration = ActionRegistration.find(params[:id])
    @action_registration.destroy

    respond_to do |format|
      format.html { redirect_to administration_action_registrations_path }
      format.json { head :no_content }
    end
  end

  def change_status
    @action_registration = ActionRegistration.find(params[:id])
    if @action_registration.status==true
      @action_registration.status=false
    else
      @action_registration.status=true
    end
    @action_registration.save
    respond_to do |format|
        format.html { redirect_to administration_action_registrations_path, notice: 'Action registration status was changed.' }
        format.json { head :no_content }      
    end
  end
end

app/controllers/administration/bodies_controller.rb
class Administration::BodiesController < AdministrationController
  
  # GET /bodies
  # GET /bodies.json
  def index
    @bodies = Body.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bodies }
    end
  end

  # GET /bodies/1
  # GET /bodies/1.json
  def show
    @body = Body.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @body }
    end
  end

  # GET /bodies/new
  # GET /bodies/new.json
  def new
    @body = Body.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @body }
    end
  end

  # GET /bodies/1/edit
  def edit
    @body = Body.find(params[:id])
  end

  # POST /bodies
  # POST /bodies.json
  def create
    @body = Body.new(params[:body])

    respond_to do |format|
      if @body.save
        format.html { redirect_to  administration_body_path(@body), notice: 'Body was successfully created.' }
        format.json { render json: @body, status: :created, location: @body }
      else
        format.html { render action: "new" }
        format.json { render json: @body.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bodies/1
  # PUT /bodies/1.json
  def update
    @body = Body.find(params[:id])

    respond_to do |format|
      if @body.update_attributes(params[:body])
        format.html { redirect_to administration_body_path(@body), notice: 'Body was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @body.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bodies/1
  # DELETE /bodies/1.json
  def destroy
    @body = Body.find(params[:id])
    @body.destroy

    respond_to do |format|
      format.html { redirect_to administration_bodies_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/administration/brands_controller.rb
class Administration::BrandsController < AdministrationController
  
  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brands }
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/new
  # GET /brands/new.json
  def new
    @brand = Brand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(params[:brand])

    respond_to do |format|
      if @brand.save
        format.html { redirect_to administration_brand_path(@brand), notice: 'Brand was successfully created.' }
        format.json { render json: @brand, status: :created, location: @brand }
      else
        format.html { render action: "new" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brands/1
  # PUT /brands/1.json
  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to administration_brand_path(@brand), notice: 'Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to administration_brands_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/administration/companies_controller.rb
class Administration::CompaniesController < AdministrationController
  COMPANY_ID = 1
  # GET /administration/companies/1
  # GET /administration/companies/1.json
  def show

  	begin
    	@company = Company.find(COMPANY_ID)
    rescue ActiveRecord::RecordNotFound
    	@company = Company.create({:description => ''})
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end    
  end

  # GET /administration/companies/1/edit
  def edit
    begin
    	@company = Company.find(COMPANY_ID)
    rescue ActiveRecord::RecordNotFound
    	@company = Company.create({:description => ''})
    end
  end

  # PUT /administration/companies/1
  # PUT /administration/companies/1.json
  def update
    @company = Company.find(COMPANY_ID)

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to administration_company_path(@company), notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/administration/contacts_controller.rb
class Administration::ContactsController < AdministrationController
  
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @Contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @Contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @Contact = Contact.new
    @Type = params[:type]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @Contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @Contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    type = params[:type]
    @Contact
    case type
    when 'Email'
      @Contact = Email.new(params[:contact])
    when 'Phone'
      @Contact = Phone.new(params[:contact]) 
    else 'Address'
      @Contact = Address.new(params[:contact])
    end    

    @Company = Company.find(1)
    @Company.contacts << @Contact

    respond_to do |format|
      if @Company.save
        format.html { redirect_to edit_administration_company_path(1), notice: 'Contact was successfully created.' }
        format.json { render json: @Contact, status: :created, location: @Contact }
      else
        format.html { render action: "new" }
        format.json { render json: @Contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @Contact = Contact.find(params[:id])
    concret_contact = nil
    if params.has_key?(:email)
      concret_contact = params[:email]
    elsif params.has_key?(:phone)
      concret_contact = params[:phone]
    elsif params.has_key?(:address)
      concret_contact = params[:address]
    end

    respond_to do |format|
      if concret_contact!=nil && @Contact.update_attributes(concret_contact)
        format.html { redirect_to edit_administration_company_path(1), notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @Contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @Contact = Contact.find(params[:id])
    @Contact.destroy

    respond_to do |format|
      format.html { redirect_to edit_administration_company_path(1) }
      format.json { head :no_content }
    end
  end
end

app/controllers/administration_controller.rb
class AdministrationController < ApplicationController
	before_filter :authenticate_user!
	layout 'administration'
	private
	  before_filter :instantiate_controller_and_action_names
	 
	  def instantiate_controller_and_action_names
	      @current_action = action_name
	      @current_controller = controller_name
	  end
end

app/helpers/administration/action_registrations_helper.rb
module Administration::ActionRegistrationsHelper
end

app/helpers/administration/bodies_helper.rb
module Administration::BodiesHelper
end

app/helpers/administration/brands_helper.rb
module Administration::BrandsHelper
end

app/helpers/administration/companies_helper.rb
module Administration::CompaniesHelper
end

app/helpers/administration/customers_helper.rb
module Administration::CustomersHelper
end

app/helpers/administration/models_helper.rb
module Administration::ModelsHelper
end

app/views/administration/projects/edit.html.erb
<h1>Editing project</h1>

<%= form_for [:administration, @project],  :html => {:multipart => true, :id => "fileupload" } do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
     <%= f.text_area :description, size: '80x5' %>
  </div>
  <div class="field">
    <%= f.label :finish_date %><br />
    <%= f.date_select :finish_date %>
  </div>  
  <%= render :partial => '/administration/project_photos/index', :locals => {:project => @project }%>
  <div class="actions">
    <%= f.submit(:class =>'btn primary start') %>
  </div>
<% end %>

<%= link_to 'Show', :controller => administration_projects_path, :action => 'show', :id => @project.id %> |
<%= link_to 'Back', administration_projects_path %>

app/views/administration/projects/index.html.erb
<h1>Listing projects</h1>

<table class="table table-striped table-hover">
<thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Finish Date</th>
    <th>Rating</th>
    <th colspan="3">Actions</th>
  </tr>
</thead>
<tbody>
<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.description %></td>
    <td><%= project.finish_date %></td>
    <td><%= project.rating %></td>
    <td><%= link_to 'Show', :controller => administration_projects_path, :action => 'show', :id => project.id %></td>
    <td><%= link_to 'Edit', :controller => administration_projects_path, :action => 'edit', :id => project.id %></td>
    <td><%= link_to 'Destroy',  
      { :controller => administration_projects_path, :action => 'destroy', :id => project.id },
      { :confirm => 'Are you sure?', :method => :delete, :remote => true} %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Project', new_administration_project_path, :class =>'btn' %>

app/views/administration/projects/new.html.erb
<h1>New project</h1>
<%= form_for [:administration, @project], :html => {:multipart => true, :id => "fileupload" } do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
     <%= f.text_area :description, size: '80x5' %>
  </div>
  <div class="field">
    <%= f.label :finish_date %><br />
    <%= f.date_select :finish_date %>
  </div>  
  <table class="table table-striped table-hover">
    <thead>        
      <tr>
        <th>Service name</th>
        <th>Selected</th>
      </tr>
    </thead>  
    <tbody>
      <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= check_box_tag "services[#{service.id}]" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="actions">
    <%= f.submit(:class =>'btn primary start') %>
  </div>
<% end %>

<%= link_to 'Back', administration_projects_path %>

app/views/administration/projects/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Name</b>
  <%= @project.name %>
</p>
<p>  
  <b>Description</b>
  <%= @project.description %><br>
</p>
<p>
  <b>Finish Date</b>
  <%= @project.finish_date %>
</p>
<p>
  <b>Rating</b>
  <%= @project.rating %>
</p>
<p>
<p>
  <b>Services</b>
  <% @project.services.each do |service|%>
  <%= link_to service.name, :controller => administration_services_path, :action => 'show', :id => service.id %>,
  <%end%>
</p>
<b>Vehicles</b><br>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
          <th>Brand</th>
          <th>Model</th>
          <th>Body</th>
          <th>Year</th>
      </tr>
    </thead>
    <tbody>
      <% @project.vehicles.each do |vehicle|%>  
      <tr>
        <td><%=vehicle.model.brand.name%></td>
        <td><%=vehicle.model.name%></td>
        <td><%=vehicle.body.name%></td>
        <td><%=vehicle.year%></td>
      </tr>
      <%end%>
    </tbody>
  </table>


<b>Photos</b></br>
<ul class="thumbnails">   
  <% @project.project_photos.each do |photo|%>
    <% if(photo.default) %>
        <li class="thumbnail" style="background-color: #08C">
           <%= image_tag photo.image.thumb('200x150#').url if photo.image %>
                 
        </li>
    <%else%>
      <li class="thumbnail">
          <%= image_tag photo.image.thumb('200x150#').url if photo.image %>
        
      </li>
    <%end%>
  <%end%>
</ul>


<%= link_to 'Edit', :controller => administration_projects_path, :action => 'edit', :id => @project.id %> |
<%= link_to 'Back', administration_projects_path %>